server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://patient-db:3306/patientdb
    username: patient_user
    password: patient_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
